### PR TITLE
Add #[must_use] suggested by Clippy

### PR DESCRIPTION
**Pull request by schneiderfelipe**
This PR adds some `#[must_use]` suggested by Clippy.

### CODE REVIEW

**Review by paulkernfeld — COMMENTED** [review]
Thanks for the PR! I have a couple questions about this:

- What bugs should this prevent?
- I don't see this suggested when I run `cargo clippy`; how did you get clippy to suggest it?

**Comment by schneiderfelipe** [comment]
> Thanks for the PR! I have a couple questions about this:
> 
>     * What bugs should this prevent?

That's just to prevent users from forgetting to use a newly created value. I think this is particularly valuable for constructors ([`return_self_not_must_use`](https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use)) and methods whose sole purpose is to produce a value ([`must_use_candidate`](https://rust-lang.github.io/rust-clippy/master/index.html#must_use_candidate)).

This PR tries to address both cases (like the constructor in [here](https://github.com/paulkernfeld/hmmm/pull/5/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R91-R92) and the pure function in [here](https://github.com/paulkernfeld/hmmm/pull/5/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R156-R159)).

Sorry for not having said all that in the PR!

>     * I don't see this suggested when I run `cargo clippy`; how did you get clippy to suggest it?

Because that's in the "pedantic" group of lints 😆, try `cargo clippy -- -W clippy::pedantic`.

**Comment by paulkernfeld** [comment]
Thanks for the detailed explanation! I'm down to merge this. Would this have helped you find a bug sooner?

**Comment by schneiderfelipe** [comment]
> Thanks for the detailed explanation! I'm down to merge this. Would this have helped you find a bug sooner?

Yes, the compiler would have alerted me about an unused value 😆
Thank you for the merge, have a great day!

**Pull request merged**
